language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  - lts/*
env:
  - TRUFFLE_DEVELOP_HOST=marketjs TRUFFLE_DEVELOP_PORT=9545
before_install:
  - pwd
  - ./scripts/travis_npm_build.sh
  - docker-compose up -d
  - docker-compose --version
  - docker-compose ps
install:
  - docker-compose exec marketjs npm install
script:
  - docker-compose exec eth-bridge scripts/wait_for_oraclize_connector.sh
  - docker-compose logs eth-bridge
  - docker-compose exec marketjs truffle migrate
  - docker-compose exec marketjs env TRUFFLE_DEVELOP_HOST="$TRUFFLE_DEVELOP_HOST" npm run test:prod
after_success:
  - docker-compose exec marketjs env TRAVIS=true TRAVIS_JOB_ID="$TRAVIS_JOB_ID" TRAVIS_BRANCH="$TRAVIS_BRANCH" TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST" npm run report-coverage
#  - docker-compose exec marketjs npm run deploy-docs
#  - docker-compose exec marketjs npm run semantic-release
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: Bf07ehAoNby7C6sY5JMBfORNQkfYQ5+amLnYPEGjEPsKPk1lqy3irUJpJrYwrqVD9YkKar5OSlpA4tjwnCB/lPwofhuD9RBrpL5xLOKFGiPCgftcmttpI27xG1otRtrHD1VZHrJMWx2/dDJCWTbDxQOPXvtQ/BLAGdMOHg/pqq+2KZJxw+31RBlMJ7ARifW9hE4B8D9a7ldvpF1sqnYIMkEh2tRC8FOyDinXI6RGByL6oeLbO6o6ybTbI7mR9PXqzXMyN/evziBFbX5zyxMfcKx+wdEH+DO/yEBTuOrAyzBzwajMqjPb9RFoDmtbxQbKf6KbsKVIUPW32QEM2xz6c4UqVXe1FydXhR0GDrY7zLu4cHu87lQneMIQ9g0FApYc+o0mLuTuQ7yOmboaU6RmxGqzBvqQH8eQaSeYNxkRu2022pHDLTSB5K0Oop6lOMbxXcZ5CZjWKGoPZGfYJnJs6r5T2ZSbr9UE+wgzPbrHmx1tSXsSveLrg2QE5+TdLmtnk1bVn7oxiEc30y3Q27yuNYg1awbXT4xchUZcBgTeuBzZtS5Osl0j3SyOpo/f2uu6YvVvJCbTpIk0LM4RxWhWnZtfiuTjiC/Y4UEQdhoypACb5KckKVjN5SL2mwXa2u3aOlArAYPgXbLrRKGd7HkCQ00XBuFH648hfWtrzXqfYag=
    on:
      branch: master
      tags: true
